spring.application.name=attendance-backend

spring.datasource.url=jdbc:mysql://localhost:3306/attendance?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Aps^50217

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Configuration (Placeholders)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=architps456@gmail.com
spring.mail.password=hlfa bwmn ccog lyzy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080